.TH darkice 1 "September 09, 2001" "DarkIce" "DarkIce live audio streamer"
.SH NAME
darkice \- an icecast / shoutcast live audio streamer
.SH SYNOPSIS
.B darkice
[options] -c config.file
.SH DESCRIPTION
.PP
.B DarkIce
is an
.B IceCast
and
.B ShoutCast
live audio streamer. It takes audio input from a
sound card, encodes it into mp3, and sends the stream to one or more
.B IceCast
and / or
.B ShoutCast
servers.

.B DarkIce
uses
.SM POSIX
real-time scheduling to keep up with sound card input.
.SM POSIX
real-time scheduling is only available if the program is run as root.
Therefore it is recommended that
.B DarkIce
is run as root.

.B DarkIce
uses the
.B Lame
mp3 encoder as a library to encode audio intput to mp3.

.SH OPTIONS
.TP
.BI "\-c " config.file
.br
.ns
.TP
.BI \-\-config= config.file
Specifies what configuration file to use.

.TP
.BI "\-v " n
.br
.ns
.TP
.BI \-\-verbosity= n
Sets the verbosity level, between 0 and 10. 0 is silent, 10 is loud.
Defaults to 1.

.TP
.BI "\-h "
.br
.ns
.TP
.BI \-\-help
Prints the help page and exists.


.SH BUGS
.PP
Lots of bugs.


.SH "SEE ALSO"
darkice.cfg(5)


.SH AUTHOR
Akos Maroy
.I <darkeye@users.sourceforge.net>


.SH ACKNOWLEDGEMENTS
Some contributions by Jim Crilly
.I <JCrilly@MSA.com>


.SH LINKS
Project homepage:
.I http://darkice.sourceforge.net/

.B IceCast
homepage:
.I http://www.icecast.org/

.B ShoutCast
homepage:
.I http://www.shoutcast.com/

.B Lame
homepage:
.I http://www.mp3dev.org/mp3/

