.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH DARKSNOW 1 "August 2005" UNIX "User Manuals"
.SH NAME
darksnow \- A simple frontend to DarkIce


.SH DESCRIPTION
\fBDarkSnow\fP is a graphical interface written in GTK+2 for the
darkice live streamer.

.SH SEE ALSO
.BR darkice (1)
.br


.SH AUTHOR
.nf
darksnow was written by Rafael Diniz <rafael@riseup.net>.

This manual page was written by Rodrigo Belem.
.fi


.SH BUGS
.nf
Send feedback or report bugs to: rafael@riseup.net
.fi


.SH COPYING

Permission is granted to copy, distribute and/or modify this manual
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation;
Permission is granted to make and distribute verbatim copies of this
manual page provided the above copyright notice and this permission
notice are preserved on all copies.

--

DarkSnow source code is free software; you can redistribute it and/or
modify it under the terms of the GNU Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

DarkSnow source code is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Please refer to the GNU Public License for more details.

You should have received a copy of the GNU Public License along with
this source code; if not, write to:
Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
USA.

.SH AVAILABILITY

The most recent version of \fIDarkSnow\fR can be obtained from its
homepage at \fIhttp://darksnow.radiolivre.org\fR.

